# uv run python -m massgen.cli --config massgen/configs/tools/filesystem/multiturn/two_gemini_flash_filesystem_multiturn.yaml
agents:
  - id: "gemini"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      cwd: "workspace1"  # Working directory for file operations
      # enable_web_search: true

  - id: "gemini2"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      cwd: "workspace2"  # Working directory for file operations

orchestrator:
    snapshot_storage: "snapshots"  # Directory to store workspace snapshots
    agent_temporary_workspace: "temp_workspaces"  # Directory for temporary agent workspaces
    session_storage: "sessions"  # Optional, defaults to "sessions". Used for multi-turn conversations to store previous rounds.

ui:
  display_type: "rich_terminal"
  logging_enabled: true

