# Azure OpenAI Multi-Agent Configuration with GPT-4.1 and GPT-5
# Usage: uv run python -m massgen.cli --config massgen/configs/azure_gpt4_gpt5.yaml "Your question here"

# Multiple agents configuration
agents:
  - id: "azure_gpt4"
    backend:
      type: "azure_openai"
      model: "gpt-4.1"  # Your Azure OpenAI deployment name for GPT-4.1
    system_message: |
      You are an expert AI assistant powered by Azure OpenAI GPT-4.1. 
      Focus on providing comprehensive and accurate responses with deep analysis.
      Collaborate effectively with other agents to solve complex problems.

  - id: "azure_gpt5"
    backend:
      type: "azure_openai"
      model: "gpt-5-chat"  # Your Azure OpenAI deployment name for GPT-5
    system_message: |
      You are an advanced AI assistant powered by Azure OpenAI GPT-5. 
      Provide innovative solutions and creative approaches to problems.
      Work collaboratively with other agents to achieve the best outcomes.

# Display configuration
ui:
  display_type: "rich_terminal"
  logging_enabled: true
  enable_final_presentation: true

# Orchestrator settings
orchestrator:
  timeout: 1800  # 30 minutes
  max_iterations: 10
