# MassGen Configuration
# Usage:
# uv run python -m massgen.cli --config configs/gemini_mcp_filesystem_test_with_claude_code.yaml " Please create a Python script with a hello world function in various fictional languages and save it directly into a file in your workspace."
agents:
  - id: "gemini_agent"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      cwd: "workspace1"  # Working directory for file operations

  - id: "claude_code"
    backend:
      type: "claude_code"
      model: "claude-sonnet-4-20250514"
      cwd: "workspace2"  # Working directory for file operations

orchestrator:
    snapshot_storage: "snapshots"  # Directory to store workspace snapshots
    agent_temporary_workspace: "temp_workspaces"  # Directory for temporary agent workspaces

ui:
  display_type: "rich_terminal"
  logging_enabled: true
