# Dual agent configuration using Notion MCP with Gemini-2.5-flash.
# Place it in your .env file: NOTION_TOKEN="your_notion_token_here"
# python -m massgen.cli --config configs/gemini_mcp_test.yaml "Generate and refine a structured Todo list for learning about multi-agent systems. After finalizing the list, add it to my Notion 'Multiagent' page under the appropriate Todo section."
agents:
  - id: "gemini-2.5-flash1"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      enable_web_search: true


      # MCP tools configuration
      mcp_servers:
        notionApi:
          type: "stdio"
          command: "npx"
          args: ["-y", "@notionhq/notion-mcp-server"]
          env:
            NOTION_TOKEN: "${NOTION_TOKEN}" 


  - id: "gemini-2.5-flash2"
    backend:
      type: "gemini"
      model: "gemini-2.5-flash"
      enable_web_search: true


      # MCP tools configuration
      mcp_servers:
        notionApi:
          type: "stdio"
          command: "npx"
          args: ["-y", "@notionhq/notion-mcp-server"]
          env:
            NOTION_TOKEN: "${NOTION_TOKEN}" 


# UI Configuration
ui:
  type: "rich_terminal"
  logging_enabled: true