# ZAI Coding Team - Four Agents (glm-4.5 / glm-4.5-air)

agents:
  - id: "architecture_glm45"
    backend:
      type: "zai"
      model: "glm-4.5"
      base_url: "https://api.z.ai/api/paas/v4/"

  - id: "claude_code_agent"
    backend:
      type: "claude_code"
      cwd: "claude_code_workspace" 

  - id: "gpt-5-nano"
    backend:
      type: "openai"
      model: "gpt-5-nano"
      text: 
        verbosity: "medium"
      reasoning:
        effort: "medium"
        summary: "auto"
      enable_web_search: true
      enable_code_interpreter: false

  # - id: "gemini2.5flash"
  #   backend:
  #     type: "gemini"
  #     model: "gemini-2.5-flash"
  #     enable_web_search: true

ui:
  display_type: "rich_terminal"
  logging_enabled: true

