# MassGen Multimodal GPT Configuration
# uv run python -m massgen.cli --config massgen/configs/basic/single/multimodal_gpt.yaml "Your question here"
agent:
  id: "response_agent"
  # system_message: "You are a helpful AI assistant powered by Google Gemini."
  backend:
    type: "openai"
    model: "gpt-5-nano"
    upload_files:
      - image_path: "image_path or image_url" #it will auto dected by backend
    # enable_code_execution: true
  system_message: "You are a helpful assistant"

# Display configuration
ui:
  display_type: "rich_terminal"
  logging_enabled: true