# MassGen Two Agent Configuration both calling the same vLLM model
agents:
  - id: "qwen1"
    backend:
      type: "vllm"
      model: "Qwen/Qwen3-0.6B"
      base_url: "http://localhost:8000/v1"
  - id: "qwen2"
    backend:
      type: "vllm"
      model: "Qwen/Qwen3-0.6B"
      base_url: "http://localhost:8000/v1"
 
ui:
  display_type: "rich_terminal"
  logging_enabled: true
